name: Dev Release on Merge to Dev

on:
    push:
        branches:
            - 'dev'

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: Install dependencies
              run: npm install -g gh

            - name: Set VERSIONING_STRATEGY
              run: echo "VERSIONING_STRATEGY=minor" >> $GITHUB_ENV

            - name: Run calculate_next_version.sh for dev branch
              id: next_version_dev
              run: |
                  chmod +x calculate_next_version.sh
                  export VERSIONING_STRATEGY=minor
                  next_version=$(./calculate_next_version.sh dev)
                  echo "::set-output name=next_version::$next_version"

            - name: Set Git committer identity
              run: |
                  git config user.email "${{ github.actor }}@users.noreply.github.com"
                  git config user.name "${{ github.actor }}"

            - name: Merge feature branch into dev
              run: git merge "${{ github.event.head_commit.id }}"

            - name: Create annotated tag on dev branch
              run: git tag -a "dev-${{ steps.next_version_dev.outputs.next_version }}" -m "${{ steps.next_version_dev.outputs.next_version }}"

            - name: Push annotated tag to remote
              run: git push origin "refs/tags/dev-${{ steps.next_version_dev.outputs.next_version }}"
              env:
                  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

            - name: Create release on dev branch
              run: |
                  gh release create "${{ steps.next_version_dev.outputs.next_version }}-dev" --generate-notes --target dev
